development:
  secret_key_base: sdfkjhsadflhawfse9f7gsergf789serg987hserg897serg897esrg

test:
  secret_key_base: seg987seg87serg87serg978hserg978hserg978serg97serg978se

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
